### ISSUE TITLE
Text resize rules

### ISSUE THREAD

**Issue by faridsabitov** [KikeSz/Method-Sketch-Plugin#3]
Hi @KikeSz,

Right now I'm trying to use method plugin as much as I can and it's already saving a couple of hours per week!

I have one idea for improvement. Right now when I'm applying the method for the text it starts to resize it by the height and the weight parameters that looks a little bit strange. In Sketch we have text resizing tools and based on the selected option, we can change only height/weight/both at a time. Here are the visuals that hopefully will be able to explain the idea in more details.

![image](https://user-images.githubusercontent.com/18511447/63803582-eb465380-c91d-11e9-8853-f1f37abb8257.png)

![image](https://user-images.githubusercontent.com/18511447/63803597-f4372500-c91d-11e9-8d1a-bd356c4220d2.png)

![image](https://user-images.githubusercontent.com/18511447/63803610-fd27f680-c91d-11e9-9daf-4c64040164e1.png)

Thank you! One of the most useful plugins for Sketch so far!

**Comment by KikeSz** [comment]
Hi @faridsabitov !

The truth is that it makes a lot of sense what you said, to be able to restrict one of the parameters so that the rounding is only in one direction looks good.

Right now I'm a bit busy but as soon as I have time I'll check if I can implement it 😉

I will try to do it but I am more designer than programmer🤪
